parameters:
  azureSubscription: ''
  scriptPath: 'src/run_tf.sh'
  artifactName: 'drop'

jobs: 
  - job: validate
    displayName: Terraform Validation
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo This is pipeline $(System.DefinitionId)
    - task: AzureCLI@1
      displayName: 'Verify Terraform Sources'
      inputs:
        azureSubscription: ${{ parameters.azureSubscription }}
        scriptPath: ${{ parameters.scriptPath }}
        arguments: '-d -f -v -p'
        addSpnToEnvironment: true
      env:
        TF_VAR_prefix=$(IaC_Shared_Variables.TF_VAR_prefix)
        __TF_backend_resource_group_name=$(IaC_Terraform_Backend_Variables.__TF_backend_resource_group_name)
        __TF_backend_location=$(IaC_Terraform_Backend_Variables.__TF_backend_location)
        __TF_backend_storage_account_name=$(IaC_Terraform_Backend_Variables.__TF_backend_storage_account_name)
        __TF_backend_storage_container_name=$(IaC_Terraform_Backend_Variables.__TF_backend_storage_container_name)
    - bash: 'git clean -fdx'
      displayName: 'Minimize Published Package'
    - publish: $(System.DefaultWorkingDirectory)
      artifact: ${{ parameters.artifactName }}
