parameters:
  azureSubscription: ''
  environmentName: '' 
  scriptPath: 'src/run_tf.sh'
  artifactName: 'drop'

jobs: 
  - deployment: tf_deploy_${{ parameters.environmentName }}
    displayName: Terraform Deploy ${{ parameters.environmentName }}
    pool:
      vmImage: 'ubuntu-latest'
    environment: ${{ parameters.environmentName }}
    strategy: 
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: ${{ parameters.artifactName }}
          - bash: |
              echo "##vso[task.setvariable variable=TF_VAR_prefix]$(IaC_Shared_Variables.TF_VAR_prefix)"
              echo "##vso[task.setvariable variable=__TF_backend_resource_group_name]$(IaC_Terraform_Backend_Variables.__TF_backend_resource_group_name)"
              echo "##vso[task.setvariable variable=__TF_backend_location]$(IaC_Terraform_Backend_Variables.__TF_backend_location)"
              echo "##vso[task.setvariable variable=__TF_backend_storage_account_name]$(IaC_Terraform_Backend_Variables.__TF_backend_storage_account_name)"
              echo "##vso[task.setvariable variable=__TF_backend_storage_container_name]$(IaC_Terraform_Backend_Variables.__TF_backend_storage_container_name)"
          - task: AzureCLI@1
            displayName: 'Verify Terraform Sources'
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              scriptPath: $(Pipeline.Workspace)/${{ parameters.artifactName }}/${{ parameters.scriptPath }}
              arguments: '-d -f -e -p ${{ parameters.environmentName }}'
              addSpnToEnvironment: true
