parameters:
  azureSubscription: ''
  environmentName: '' 
  scriptPath: 'src/run_tf.sh'
  artifactName: 'drop'

jobs: 
  - deployment: tf_deploy_${{ parameters.environmentName }}
    displayName: Terraform Deploy ${{ parameters.environmentName }}
    pool:
      vmImage: 'ubuntu-latest'
    environment: ${{ parameters.environmentName }}
    strategy: 
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: ${{ parameters.artifactName }}
          - task: AzureCLI@1
            displayName: 'Verify Terraform Sources'
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              scriptPath: $(Pipeline.Workspace)/${{ parameters.artifactName }}/${{ parameters.scriptPath }}
              arguments: '-d -f -e -p ${{ parameters.environmentName }}'
              addSpnToEnvironment: true
            env:
              TF_VAR_prefix=$(IaC_Shared_Variables.TF_VAR_prefix)
              __TF_backend_resource_group_name=$(IaC_Terraform_Backend_Variables.__TF_backend_resource_group_name)
              __TF_backend_location=$(IaC_Terraform_Backend_Variables.__TF_backend_location)
              __TF_backend_storage_account_name=$(IaC_Terraform_Backend_Variables.__TF_backend_storage_account_name)
              __TF_backend_storage_container_name=$(IaC_Terraform_Backend_Variables.__TF_backend_storage_container_name)
